Reinforced.Typings/Attributes/TsBaseParamAttribute.cs, Reinforced.Typings/Properties/AssemblyInfo.cs, Reinforced.Typings/WriterWrapper.cs
Makes Reinforced.Typings CLS compliant by marking assembly with appropriate attribute and fixes CLS-related build warnings via attributes and additional constructors. This enables usage of Reinforced.Typings in projects that need to be CLS compliant (e.g. ASP.NET 5 projects which run on Linux)
=> CLS Compliance

package/build/Reinforced.Typings.targets
We are using TreatWarningsAsErrors in our CI to prevent accidential regressions. This PR uses the default msbuild TreatWarningsAsErrors property to conditionally generate errors instead of warnings, which will fail the build if someone forgot to revert the temporary RtDisable or RtBypassTypeScriptCompilation parameter.
=> Generate Error instead of warning if TreatWarningsAsErrors is set

Reinforced.Typings.Cli/Bootstrapper.cs
Removed addding of '.dll' extension inside `CurrentDomainOnAssemblyResolve`, as `LookupAssemblyPath` will handle missing extension by itself. This change fixes resolve of referenced `.exe` assembly. Resolves #44.
=> Removed adding of '.dll' extension during assembly resolves.

README.md
The info about critical bugs was a bit hidden so I gave it some flare. And fixed the typo.
=> Add fire to the version warning and fix typo

Reinforced.Typings.Tests/Reinforced.Typings.Tests.csproj, Reinforced.Typings.Tests/SpecificCases/SpecificTestCases.TsFunctionWorksWithEnum.cs, Reinforced.Typings/Generators/ParameterCodeGenerator.cs
Enum default value is not able to generate in typescript, in a right way.
Bug related with 
https://github.com/reinforced/Reinforced.Typings/issues/75
=> fix of enum default value assignment

xmls/Reinforced.Typings.targets
Adds the compilation and build target dependencies only if the settings.xml file is present. Issue details are here - https://github.com/reinforced/Reinforced.Typings/issues/80
=> Adding compilation and build dependencies only if the settings.xml is present

Reinforced.Typings/TypeBlueprint.cs
The code is taken almost verbatim from Json.Net (MIT license).
Before the fix:
```
> ConvertToCamelCase("X1_2AB_")
"xab"
```
After:
```
> ConvertToCamelCase("X1_2AB_")
"x1_2AB_"
```
=> Fix numbers and underscores in ConvertToCamelCase

Reinforced.Typings.Tests/Reinforced.Typings.Tests.csproj, Reinforced.Typings.Tests/SpecificCases/SpecifiicTestCases.UnresolvedToUnknown.cs, Reinforced.Typings/Attributes/TsGlobalAttribute.cs, Reinforced.Typings/Exceptions/ErrorMessages.cs, Reinforced.Typings/Fluent/GlobalConfigurationBuilder.cs, Reinforced.Typings/GlobalParameters.cs, Reinforced.Typings/TypeResolver.cs
This PR adds a Global Configuration Parameter which when set to true will export unresolved types as 'unknown' instead of the current behaviour of 'any'. The default value is false.
The intention is is to increase safety by preventing unintended 'any' types from being generated.
=> Export unresolved types as 'unknown'

Reinforced.Typings.Integrate/RtCli.cs
Hi I'm converting .net 4.8 project to new [SDK-style csproj](https://docs.microsoft.com/en-gb/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2019) so my .csproj look like that now (simplified):
```
<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
<TargetFramework>net48</TargetFramework>
</PropertyGroup>
<ItemGroup>
<Content Include="Reinforced.Typings.settings.xml" />
</ItemGroup>
</Project>
```
But now I get this error:
```
Error	MSB6004	The specified task executable location "C:\Users\Mariusz\.nuget\packages\reinforced.typings\1.5.3\tools\net48\rtcli.exe" is invalid.	Analyx.CWX.InternalApi	C:\Users\Mariusz\.nuget\packages\reinforced.typings\1.5.3\build\Reinforced.Typings.targets	59	
```
This should fix the error.
=> Support "net48" TargetFramework.

Reinforced.Typings/FilesOperations.cs
Hi @pavel-b-novikov,
I would like to expose FilesOperations, which would allow to trigger generating typescript files at runtime (i.e. as discussed here: https://github.com/reinforced/Reinforced.Typings/issues/156#issuecomment-653226508)
=> use public access modifier for FilesOperations

Reinforced.Typings/Ast/TypeNames/RtTuple.cs
Hi, 
this PR adds the `ToString()` method to the `RtTuple` class (it is already implemented in the other AST type name classes). 
This is useful for custom code generators.
=> Add ToString to RtTuple

Reinforced.Typings.Tests/Reinforced.Typings.Tests.csproj, Reinforced.Typings.Tests/SpecificCases/SpecificTestCases.InheritDoc.cs, Reinforced.Typings.Tests/TypeNameEqualityComparer.cs, Reinforced.Typings/Ast/RtJsdocNode.cs, Reinforced.Typings/Ast/TypeNames/RtSimpleTypeName.cs, Reinforced.Typings/Generators/ClassAndInterfaceGeneratorBase.cs, Reinforced.Typings/Generators/ConstructorCodeGenerator.cs, Reinforced.Typings/Generators/EnumGenerator.cs, Reinforced.Typings/Generators/MethodCodeGenerator.cs, Reinforced.Typings/Generators/PropertyCodeGenerator.cs, Reinforced.Typings/Visitors/TypeScript/Types/TypeScriptExportVisitor.RtSimpleTypeName.cs, Reinforced.Typings/Xmldoc/DocumentationManager.cs, Reinforced.Typings/Xmldoc/Model/DocumentationMemberExtensions.cs, Reinforced.Typings/Xmldoc/Model/Model.cs
`<inheritdoc/>` in XML docs is now carried over to JSDOC as `@inheritdoc`.
Don't know whether this library needs support of `<inheritdoc cref="SomeClass"/>` or how to resolve the reference under `cref`.
=> Support inheritdoc in XML documentation

Reinforced.Typings.Tests/SpecificCases/SpecificTestCases.AutoOptionalWithCompilerNullable.cs, Reinforced.Typings/Generators/ParameterCodeGenerator.cs, Reinforced.Typings/Generators/PropertyCodeGenerator.cs, Reinforced.Typings/TypeExtensions.cs
With C# compiler higher than 8.0 a new flag has been introduced to invert the nullability of reference types.
The flag can be set globally per project or for each file.
The file flag is:
```
#nullable enable
```
If this flag is enabled, reference types are not implicitly nullable anymore. Nullability must be set explicitly. In such cases, the types should be exported with this explicit nullability to TypeScript too.
The compiler attaches additional attributes to the member/parameter information. This way, the generated code is stil backwards compatible with older C# IDL versions.
If this flag is not set, then the new code will not take any effect as the additional attributes will not be not attached.
see:
* https://github.com/dotnet/roslyn/blob/master/docs/features/nullable-metadata.md
* …
=> detect nullable environment on C# >= 8.0

Reinforced.Typings.Tests/SpecificCases/SpecificTestCases.AutoAsync.cs, Reinforced.Typings/Ast/TypeNames/RtAsyncType.cs, Reinforced.Typings/Generators/MethodCodeGenerator.cs, Reinforced.Typings/TypeExtensions.cs, Reinforced.Typings/TypeResolver.cs, Reinforced.Typings/Visitors/TypeScript/TypeScriptExportVisitor.RtFunction.cs, Reinforced.Typings/Visitors/TypeScript/TypeScriptExportVisitor.cs, Reinforced.Typings/Visitors/TypeScript/Types/TypeScriptExportVisitor.RtAsyncType.cs, Reinforced.Typings/Visitors/VisitorBase.cs
Converting interfaces that declare async methods via return type
`Task` fails currently. The result does not contain any Promise
return type, but just `any`. A return value of `Task` is an
implicit declaration of asynchronous function. Since
interfaces to not contain implementation of functions, the
explicit defining keyword `async` is not supported.
So far, automatic detection of async functions was insufficient.
This commit introduces a new return type `RtAsyncType` that
handles proper creation of TypeScript type declaration.
Once a method returns `Task` and `AutoAsync` flag is enabled,
the return value `Promise` is used with TypeScript code.
If the  `AutoAsync` flag is not enabled, then the async
(Promise) value is unfolded instead of just converted to
`any`.
Converting an empty …
=> fix #182: introduce RtAsyncType to handle "Promise" return type

Reinforced.Typings.Tests/SpecificCases/SpecificTestCases.Fields.cs, Reinforced.Typings/Fluent/MemberBuilders/MemberExportBuilder.Field.cs, Reinforced.Typings/Fluent/MemberExtensions/MemberExportExtensions.Property.cs, Reinforced.Typings/Fluent/TypeBuilders/TypeExportBuilder.ClassOrInterface.cs, Reinforced.Typings/Fluent/WithExtensions/WithExtensions.Fields.cs
A field export builder is being introduced to provide the properly typed `Member` property. Fields use
`FieldInfo`, whereas properties use `PropertyInfo`. So, using original `PropertyExportBuilder` with accessing the member info leads to a type cast exception.
Since the new `FieldExportBuilder` is a descendant of `PropertyExportBuilder`, it can be used as a
replacement seemlesly - where needed. All `withField...` are changed to use that new builder, giving consumers of the export config to access `FieldInfo`.
fixes: #190
=> fix: introduce `FieldExportBuilder`

Reinforced.Typings.Tests/SpecificCases/SpecificTestCases.FunctionWithParamInitialiser.cs, Reinforced.Typings/Visitors/TypeScript/TypeScriptExportVisitor.RtArgument.cs
Methods in interface may not have parameter default values ("initialisers"). TypeScript compiler 3.9.7 emits error TS2371 if such a default value is being found.
Such default value makes a parameter optional. So, instead of emitting the default value, the parameter is marked with "?". Then in can be omitted from the list of parameters as it would be with a default value.
fixes #191
=> fix: omit parameter initialiser in interfaces

Reinforced.Typings.Tests/SpecificCases/SpecificTestCases.ThirdPartyWithBaseClass.cs, Reinforced.Typings/Generators/ClassAndInterfaceGeneratorBase.cs
If a class-type is exported as an interface but derives from a third-party base class, a type cast exception was thrown.
The exported expected a class-node (`RtClass`) during the export but apparently it is a `RtInterface`, because the type is
being exported as interface.
So, base classes are added to the list of `implementees` instead as there is no base class for an interface.
fixes: #189
=> base class is treated as base interface if class is exported as interface

Reinforced.Typings.Tests/SpecificCases/SpecificTestCases.GenericGuidDictionary.cs, Reinforced.Typings/TypeResolver.cs
Fixes issue #211 by checking the actual type instead of object equality.
This fixes #211.
=> fix RT0007 bug #211

Reinforced.Typings.NETCore.sln, Reinforced.Typings.Tests/Reinforced.Typings.Tests.NETCore.csproj, TestFluentAssembly/TestFluentAssembly.NETCore.csproj
Some project files were missing to build the whole project
for .NET core. This is needed to build the project
on other platforms, like Mac OS or Linux.
=> feat:(build) add missing .NET core project files

Reinforced.Typings.Tests/SpecificCases/SpecificTestCases.KpKozakIssueWithInheritance.cs
A test failes on MacOS since path separator `\`
was used literally instead of using the global constant
`Path.DirectorySeparatorChar`.
=> fix:(test) use `DirectorySeparatorChar` instead of `\`

stuff/Reinforced.Typings.targets
When Reinforced.Typings.targets creates the RtSettingsXml propery, it will now check it it has been defined previously.
If it has not been defined previously, it will construct RtSettingsXml to point to the default location.
This fixes #209.
=> Allow a custom Reinforced.Typings.settings.xml location.

stuff/Reinforced.Typings.nuspec
Mark as development dependency by adding `<developmentDependency>true</developmentDependency>` to `nuspec`.
This is in line with expectations from the consumers. This is also how other packages are marked, e.g.:
- Microsoft.VisualStudio.Threading.Analyzers
- Meziantou.Analyzer
- IDisposableAnalyzers
- AsyncFixer
=> Mark as `developmentDependency`

stuff/Reinforced.Typings.targets
Fixes #266, partially addresses #235
As someone who a) wants to disable mutation of source code on my build server, because it's a volatile thing that I don't want, and also b) wants to be conservative and treat my [unintentional] warnings as errors, I cannot do that because this always fails:
```
dotnet build --property:RtDisable=true --property:TreatWarningsAsErrors=true
```
The recommendation here is to simply decouple these properties and only `Message` when something is disabled as an intentional act.  
Also consider:
- Alternate `Warning` type with a unique error code for suppression, see #235.  I've opted for `Message` type in my recommendation.
=> remove conditional error when disabling, treating warnings as errors

Reinforced.Typings.Tests/SpecificCases/SpecificTestCases.RemarksDocs.cs, Reinforced.Typings/Xmldoc/Model/DocumentationMemberExtensions.cs, Reinforced.Typings/Xmldoc/Model/Model.cs
This PR adds the `DocumentationRemarks` type which stores the content from XmlDocs `<remarks />` section.
The behaviour of the emitted code is not changed:
* `DocumentationMember.GetDocumentationMember` will return `null` if a member has only a ´<remarks />` section but no other XmlDoc related data
* The text content from the `<remarks />` section is just stored in the `DocumentationMember` but not used in any provided code generator implementation.
However, when writing a custom code generator, the content of the `<remarks />` section is now available.
This fixes #290.
=> Add DocumentationRemarks to the DocumentationMember 
